apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: rhte-camelk-gitea
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"  
spec:
  giteaVolumeSize: 4Gi
  postgresqlVolumeSize: 4Gi
  giteaSsl: true
  giteaAdminUser: rhte-camelk
  giteaAdminPassword: ""
  giteaAdminPasswordLength: 8
  giteaAdminEmail: opentlc-mgr@redhat.com
  giteaCreateUsers: true
  giteaGenerateUserFormat: "user%d"
  giteaUserNumber: 10
  giteaUserPassword: openshift
  giteaMigrateRepositories: true
  giteaRepositoriesList:
  - repo: https://github.com/agiertli/rhte-camelk-lab-instructions.git
    name: camelk-user-repository
    private: false
