{{- range $key := .Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secret-role
  namespace: {{.name}}-dev
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - create
  - delete
  - patch
  - update
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sealed-secret-role
  namespace: {{.name}}-prod
rules:
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - create
  - delete
  - patch
  - update
  - list  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secret-user-admin
  namespace: {{.name}}-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secret-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{.name}}


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sealed-secret-user-admin
  namespace: {{.name}}-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secret-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{.name}}  
{{- end }}