{{- range $key := .Values.users }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab5-{{ .name }}-charts-dev
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{.name}}-dev
    server: https://kubernetes.default.svc
  project: rhte-camelk-tooling   
  source:
    helm:
      valueFiles:
       - dev/values.yaml
    path: labs/lab5/charts
    repoURL: http://rhte-camelk-gitea.gitea.svc.cluster.local:3000/{{.name}}/camelk-user-repository.git
    targetRevision: dev
  syncPolicy:
    syncOptions:
     - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab5-{{ .name }}-charts-prod
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{.name}}-prod
    server: https://kubernetes.default.svc
  project: rhte-camelk-tooling   
  source:
    helm:
      valueFiles:
       - prod/values.yaml  
    path: labs/lab5/charts
    repoURL: http://rhte-camelk-gitea.gitea.svc.cluster.local:3000/{{.name}}/camelk-user-repository.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
     - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab5-{{ .name }}-secrets-prod
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{.name}}-prod
    server: https://kubernetes.default.svc
  project: rhte-camelk-tooling   
  source:
    path: labs/lab5/secrets/prod
    repoURL: http://rhte-camelk-gitea.gitea.svc.cluster.local:3000/{{.name}}/camelk-user-repository.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
     - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true        
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab5-{{ .name }}-secrets-dev
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{.name}}-dev
    server: https://kubernetes.default.svc
  project: rhte-camelk-tooling   
  source:
    path: labs/lab5/secrets/dev
    repoURL: http://rhte-camelk-gitea.gitea.svc.cluster.local:3000/{{.name}}/camelk-user-repository.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
     - SkipDryRunOnMissingResource=true
    automated:
      selfHeal: true              
{{- end }}