apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: gitops-1.6
  installPlanApproval: Automatic
  startingCSV: openshift-gitops-operator.v1.6.3
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  name: openshift-gitops-operator