{{- range $key := .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.name}}-git-credentials-secret
  namespace: {{.name}}-dev
  labels:
    controller.devfile.io/git-credential: 'true' 
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-path: /etc/secret 
    rgocd.argoproj.io/sync-wave: "-1"    
stringData:
  credentials: http://{{.name}}:openshift@rhte-camelk-gitea.gitea.svc.cluster.local:3000
{{- end }}
