---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: community-camel-k-instructor
  namespace: camelk-instructor
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"  
spec:
  channel: stable
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace

{{- range $key := .Values.users }}
--- 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{.name}}-dev-community-camel-k
  namespace: {{.name}}-dev
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"  
spec:
  channel: stable
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace
  packageOveride:
    packageOverrides:
      path: "status.build.baseImage"
      value: 'docker.io/adoptopenjdk/openjdk11:latest'
{{ end }}

{{- range $key := .Values.users }}
--- 
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{.name}}-prod-community-camel-k
  namespace: {{.name}}-prod
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"  
spec:
  channel: stable
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace
{{ end }}